executor: "CeleryExecutor"

dags:
  gitSync:
    enabled: false

webserver:
  webserverConfig: |
    from airflow import configuration as conf
    conf.set('webserver', 'worker_log_server_port', '8793')
  defaultUser:
    enabled: true
    username: admin
    password: admin
  service:
    type: ClusterIP
    port: 8080
  baseUrl: http://localhost:8080
  persistence:
    enabled: true
    size: 10Gi
    existingClaim: airflow-data-pvc

logs:
  persistence:
    enabled: true
    size: 1Gi

triggerer:
  enabled: true

redis:
  enabled: true

workers:
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
    existingClaim: airflow-data-pvc
  env:
    - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT
      value: "8793"
    - name: AIRFLOW__LOGGING__WORKER_LOG_SERVER_HOST
      value: "0.0.0.0"
    - name: AIRFLOW__LOGGING__REMOTE_LOGGING
      value: "True"
    - name: AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER
      value: "/opt/airflow/logs"
    - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
      value: "local_remote_logs"
    - name: AIRFLOW__LOGGING__TASK_LOG_READER
      value: "task"

scheduler:
  persistence:
    enabled: true
    size: 10Gi
    existingClaim: airflow-data-pvc