executor: CeleryExecutor

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/imguilherme/airflow-dags.git"
    branch: main
    subPath: "dags"
    depth: 1
    wait: 60

webserver:
  webserverConfig: |
    from airflow import configuration as conf
    conf.set('webserver', 'worker_log_server_port', '8793')
  defaultUser:
    enabled: true
    username: admin
    password: admin
  service:
    type: LoadBalancer

logs:
  persistence:
    enabled: true
    size: 1Gi

triggerer:
  enabled: true

redis:
  enabled: true

workers:
  replicas: 1

# Configuração do volume persistente para dados
volumes:
  - name: airflow-data
    persistentVolumeClaim:
      claimName: airflow-data-pvc

volumeMounts:
  - name: airflow-data
    mountPath: /opt/airflow/data
    subPath: data